### PR TITLE
Update to version 6.1.2, rerender, make CI more efficient

### LINKED ISSUE #28: Are you going to distribute version 6?
### Comment:

Libcint 6 has faster range-separated integrals. It'd be nice if it were available on conda-forge!

### PR DESCRIPTION
**Pull request by chillenb**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Closes #27
Closes #26
Closes #25
Closes #24

@BastianZim 
I added python and numpy to force_ignore_keys since they're only used to test the package, not to build it. This saves CI resources.

### CODE REVIEW

**Comment by chillenb** [comment]
Don't know why powerpc wouldn't build on Travis. Looks like the job was queued but never started up.

**Comment by BastianZim** [comment]
> Don't know why powerpc wouldn't build on Travis. Looks like the job was queued but never started up.

Travis is very flaky and fails constantly. It has nothing to do with the software itself generally. I restarted it.

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Huh, is it just me or did the tests only run on Travis?

**Comment by BastianZim** [comment]
@conda-forge-admin, please restart ci

**Comment by chillenb** [comment]
Travis isn't building the ppc64le package again...

@conda-forge-admin, please restart ci

**Comment by BastianZim** [comment]
> Travis isn't building the ppc64le package again...

That will happen many times... We can also cross compile if it doesn't work.

**Comment by chillenb** [comment]
Success!! Packages uploaded.

**Pull request merged**
